services:
  web:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.ui
    ports:
      - "80:80"

  customer-assistant:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.customer-assistant
    ports:
      - "8080:80"
